# Generated by Django 5.2.4 on 2026-06-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_organization_invoice_payment_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='DRAFT', max_length=20),
        ),
    ]
