# Generated by Django 5.2.4 on 2026-06-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='organization',
            name='invoice_prefix',
            field=models.CharField(default='ANV', max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/signatures/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='stamp',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/stamps/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/logo/'),
        ),
    ]
