# Generated by Django 5.2.4 on 2026-06-21 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_organization_account_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
        migrations.AlterField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoices.organization'),
            preserve_default=False,
        ),
    ]
