# Generated by Django 6.0.7 on 2026-08-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_delete_companyprofile_alter_customer_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
