# Generated by Django 6.0.7 on 2026-08-03 05:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoiceitem_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='receipt',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='receipt',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.organization'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('BANK', 'Bank Transfer'), ('CASH', 'Cash'), ('POS', 'POS'), ('CHEQUE', 'Cheque'), ('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave')], default='BANK', max_length=20)),
                ('payment_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.organization')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='invoices.payment'),
        ),
    ]
