# Generated by Django 6.0.7 on 2026-08-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_alter_invoiceitem_description_alter_invoiceitem_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minimum_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
