# Generated by Django 6.0.7 on 2026-08-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_alter_payment_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='deployment_phase',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
