# Generated by Django 6.0.7 on 2026-08-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_alter_invoice_deployment_phase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'status'], name='invoices_in_organiz_01efe4_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'invoice_date'], name='invoices_in_organiz_3f7f60_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'due_date'], name='invoices_in_organiz_69db93_idx'),
        ),
    ]
