# Generated by Django 6.0.7 on 2026-08-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_invoice_inventory_updated_invoice_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_stockable',
            field=models.BooleanField(default=True),
        ),
    ]
