# Generated by Django 6.0.7 on 2026-08-09 11:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_product_is_stockable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maximum_stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
