# Generated by Django 6.0.7 on 2026-08-15 11:58

import django.db.models.deletion
from django.db import migrations, models


def create_system_roles_and_assign_memberships(apps, schema_editor):
    Role = apps.get_model('invoices', 'Role')
    OrganizationMembership = apps.get_model('invoices', 'OrganizationMembership')

    roles_data = [
        {
            "name": "Administrator",
            "slug": "administrator",
            "description": "Full administrative access to organization resources",
            "is_system_role": True,
        },
        {
            "name": "Accountant",
            "slug": "accountant",
            "description": "Financial management, invoices, payments, and receipts",
            "is_system_role": True,
        },
        {
            "name": "Sales Officer",
            "slug": "sales-officer",
            "description": "Quotations, invoices, and sales management",
            "is_system_role": True,
        },
        {
            "name": "Inventory Officer",
            "slug": "inventory-officer",
            "description": "Inventory, GRN, GIN, stock transfers and adjustments",
            "is_system_role": True,
        },
        {
            "name": "Purchase Officer",
            "slug": "purchase-officer",
            "description": "Purchase orders and vendor management",
            "is_system_role": True,
        },
    ]

    admin_role = None
    for rdata in roles_data:
        role_obj, _ = Role.objects.get_or_create(
            slug=rdata["slug"],
            defaults=rdata
        )
        if rdata["slug"] == "administrator":
            admin_role = role_obj

    if admin_role:
        OrganizationMembership.objects.filter(role__isnull=True).update(role=admin_role)


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_organizationmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('slug',), name='unique_role_slug')],
            },
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='invoices.role'),
        ),
        migrations.RunPython(
            create_system_roles_and_assign_memberships,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='invoices.role'),
        ),
    ]
