# Generated by Django 6.0.7 on 2026-08-15 12:21

from django.db import migrations, models


def seed_permissions_and_assign_roles(apps, schema_editor):
    Permission = apps.get_model('invoices', 'Permission')
    Role = apps.get_model('invoices', 'Role')

    from invoices.permissions import PERMISSION_DEFINITIONS, ROLE_SYSTEM_PERMISSIONS

    perm_map = {}
    for pdata in PERMISSION_DEFINITIONS:
        perm_obj, _ = Permission.objects.update_or_create(
            code=pdata["code"],
            defaults={
                "name": pdata["name"],
                "description": pdata["description"],
                "module": pdata["module"],
                "action": pdata["action"],
                "is_active": True,
            }
        )
        perm_map[pdata["code"]] = perm_obj

    # 1. Administrator gets all permissions
    admin_role = Role.objects.filter(slug="administrator").first()
    if admin_role:
        admin_role.permissions.set(Permission.objects.all())

    # 2. Other system roles get their specific permissions
    for role_slug, perm_codes in ROLE_SYSTEM_PERMISSIONS.items():
        role_obj = Role.objects.filter(slug=role_slug).first()
        if role_obj:
            assigned_perms = [perm_map[code] for code in perm_codes if code in perm_map]
            role_obj.permissions.set(assigned_perms)


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0023_role_organizationmembership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['module', 'action', 'name'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='invoices.permission'),
        ),
        migrations.RunPython(
            seed_permissions_and_assign_roles,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
