# Generated by Django 6.0.7 on 2026-08-15 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0024_permission_role_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('style', models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('minimal', 'Minimal')], default='modern', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_templates', to='invoices.organization')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'unique_together': {('organization', 'slug')},
            },
        ),
    ]
