# Generated by Django 6.0.7 on 2026-08-17 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0025_quotationtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='invoices.quotationtemplate'),
        ),
    ]
