# Stock Movement Types Constants

MOVEMENT_TYPE_OPENING = "OPENING"
MOVEMENT_TYPE_PURCHASE = "PURCHASE"
MOVEMENT_TYPE_SALE = "SALE"
MOVEMENT_TYPE_SALE_RETURN = "SALE_RETURN"
MOVEMENT_TYPE_PURCHASE_RETURN = "PURCHASE_RETURN"
MOVEMENT_TYPE_TRANSFER_IN = "TRANSFER_IN"
MOVEMENT_TYPE_TRANSFER_OUT = "TRANSFER_OUT"
MOVEMENT_TYPE_ADJUSTMENT_IN = "ADJUSTMENT_IN"
MOVEMENT_TYPE_ADJUSTMENT_OUT = "ADJUSTMENT_OUT"
MOVEMENT_TYPE_DAMAGE = "DAMAGE"
MOVEMENT_TYPE_EXPIRED = "EXPIRED"

MOVEMENT_TYPE_CHOICES = (
    (MOVEMENT_TYPE_OPENING, "Opening Stock"),
    (MOVEMENT_TYPE_PURCHASE, "Purchase Receive"),
    (MOVEMENT_TYPE_SALE, "Sale Issue"),
    (MOVEMENT_TYPE_SALE_RETURN, "Sale Return"),
    (MOVEMENT_TYPE_PURCHASE_RETURN, "Purchase Return"),
    (MOVEMENT_TYPE_TRANSFER_IN, "Transfer In"),
    (MOVEMENT_TYPE_TRANSFER_OUT, "Transfer Out"),
    (MOVEMENT_TYPE_ADJUSTMENT_IN, "Stock Adjustment (Increase)"),
    (MOVEMENT_TYPE_ADJUSTMENT_OUT, "Stock Adjustment (Decrease)"),
    (MOVEMENT_TYPE_DAMAGE, "Damaged Stock Write-off"),
    (MOVEMENT_TYPE_EXPIRED, "Expired Stock Write-off"),
)
