# Generated by Django 6.0.7 on 2026-08-09 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_goodsissuenote_goodsissuenoteitem_goodsreceivednote_and_more'),
        ('purchases', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednote',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='purchases.purchaseorder'),
        ),
    ]
