# Generated by Django 6.0.7 on 2026-08-09 11:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_goodsreceivednote_purchase_order'),
        ('invoices', '0021_product_maximum_stock_product_minimum_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('OUT_OF_STOCK', 'Out of Stock'), ('LOW_STOCK', 'Low Stock'), ('OVERSTOCK', 'Overstock')], max_length=30)),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='invoices.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='invoices.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
