# Generated by Django 6.0.7 on 2026-08-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockalert'),
        ('invoices', '0027_quotation_issued_at_quotation_issued_by'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventoryitem',
            name='unique_product_warehouse_location',
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', True)), fields=('product', 'warehouse'), name='unique_product_warehouse_without_location'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('product', 'warehouse', 'location'), name='unique_product_warehouse_location'),
        ),
    ]
