# Generated by Django 6.0.7 on 2026-08-19 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_inventoryitem_unique_product_warehouse_location_and_more'),
        ('invoices', '0027_quotation_issued_at_quotation_issued_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsissuenote',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_notes', to='invoices.invoice'),
        ),
    ]
